### ISSUE TITLE
Amount is wrong when exceeding boundaries until reload

### ISSUE THREAD

**Issue by schinken** [hackerspace-bootstrap/strichliste-web#54]
On commit c1e5f62 for issue #22 I introduced a bug when the user exceeds the account boundaries. The value is substracted/added on the client side to appear more instant

I think we have to check the boundaries on the client side not just on the server side for this action, using the /settings API endpoint.

**Comment by breti** [comment]
Same if API is not reachable when user tries to pay. Value changes, but an error message is shown. Not sure if a separate issue is needed to deal with this.

**Comment by schinken** [comment]
Yep, it's the same

**Comment by schinken** [comment]
Reminder for myself: Disable/Remove payment buttons if limit is reached or has been exceeded
