### ISSUE TITLE
Set focus on input field in custom transactions dialog

### ISSUE THREAD

**Issue by breti** [hackerspace-bootstrap/strichliste-web#57]
When the custom transactions dialog is opened, the input field for the amount should get the focus.

**Comment by schinken** [comment]
Actually, the correct attribute is set: https://github.com/hackerspace-bootstrap/strichliste-web/blob/master/src/partials/customTransaction.html#L12

But somehow android ignores that. Trying to workaround..

**Comment by breti** [comment]
Firefox 38.0.1 on windows ignores it as well.
