### ISSUE TITLE
Metrics bar charts are hidden until mouse hovers over bar

### ISSUE THREAD

**Issue by breti** [hackerspace-bootstrap/strichliste-web#60]
On the metrics page the bar charts are hidden initially. They are shown as soon as one hovers over one of the bars on each bar chart.

Same in firefox and chrome (both most current release versions).

Reproducible with your demo installation (http://demo.hackerspace-bootstrap.org/strichliste-web/#/metrics) as well.

![strichliste_-_2015-06-28_11 29 12](https://cloud.githubusercontent.com/assets/3628895/8395832/06eee72c-1d89-11e5-9565-e2c66733b52b.png)
![strichliste_-_2015-06-28_11 29 38](https://cloud.githubusercontent.com/assets/3628895/8395831/06ec5fd4-1d89-11e5-894e-1d3994f30be0.png)

**Comment by schinken** [comment]
This issue appeared after the update of angularJS. Let me investigate this

**Comment by schinken** [comment]
I decided to migrate from Chart.js to angular-charts. See #61. I'll close that issue if it's resolved
