### ISSUE TITLE
0.00-EUR-account sometimes shown in red

### ISSUE THREAD

**Issue by breti** [hackerspace-bootstrap/strichliste-web#66]
Sometimes 0.00-EUR-accounts are shown in red, not black. Seems to be a rounding issue.

Please see this example. Database dump available upon request.

![strichliste_-_2015-08-08_08 07 49_hidden](https://cloud.githubusercontent.com/assets/3628895/9151789/9bc1f69e-3e10-11e5-988f-b991add2885a.png)

**Comment by breti** [comment]
We should move this issue to the API, because the API returns -8.881784197001252e-16 instead of 0 as "balance" value.

I think you should store INTEGER cent values instead of REAL euro values to work around floating point issues?

**Comment by seriousManual** [comment]
would prefer this solution as well though it would oppose implementing other currencies like bitcoin where more precise floating point numbers are crucial.

it also recognized it as a common practice to treat every floating point number < 0.00001 as 0 due to floating point inaccuracy

**Comment by schinken** [comment]
Fixed in strichliste 2. Will be ready soon :)
