### ISSUE TITLE
Filter by keystroke

### ISSUE THREAD

**Issue by Ps0ke** [hackerspace-bootstrap/strichliste-web#67]
A user should be able to press (alphanumeric) keys and the view should then filter only nicks starting whit (or containing?) the letters pressed. When only one nick is left, the view could automatically switch to value selection/booking for that nick.

**Comment by schinken** [comment]
Snounds good! Will implement that early

**Comment by schinken** [comment]
Moved to https://github.com/strichliste/strichliste/issues/24
