### ISSUE TITLE
Add description to transcation

### ISSUE THREAD

**Issue by schinken** [hackerspace-bootstrap/strichliste-web#78]
So you can say "+4.99 for buying dish washer tabs for space"

**Comment by NicoHood** [comment]
In our local hackerspace someone added this feature. As far as I know this was based on 1.4.3. You can find the change here:
https://github.com/hackerspace-bootstrap/strichliste/compare/master...c3pb:snowball

However this issue belongs to the backend.

**Comment by NicoHood** [comment]
Fixed in https://github.com/hackerspace-bootstrap/strichliste-web/pull/82

**Comment by schinken** [comment]
Strichliste 2 also supports that. Closing that issue here

**Comment by NicoHood** [comment]
I would not close all those issues here, people might want to keep on using strichliste1. Just because another repository exists, does not mean this one has zero bugs. I think its a bad idea to close all bugs, especially if version2 is not yet mature.

**Comment by schinken** [comment]
strichliste 2 has an importer for data from strichliste 1, so moving there would be easy. Version 2 will be released in the coming (i guess 2) weeks.

**Comment by schinken** [comment]
ok, maybe a bit "pre-mature" closing of issues, but at the end i sure don't want to support strichliste 1 anymore ;)
