### ISSUE TITLE
Missing bundles for all releases after v1.6.0

### ISSUE THREAD

**Issue by morbidick** [hackerspace-bootstrap/strichliste-web#89]
Hi,
there are no bundles on the release page for the last releases, i couldn't find any issues in the travis logs. We will deploy with the older releases for now but it would be nice to get a current build ;)

**Comment by schinken** [comment]
currently working on strichliste2 https://github.com/strichliste/server - but I may can tag another release for you

**Comment by morbidick** [comment]
that would be nice thx, gonna have a look at the rewrite :)

**Comment by schinken** [comment]
Fixed: https://github.com/hackerspace-bootstrap/strichliste-web/releases/tag/v1.7.2

Sorry for the wait. While setting up travis-ci for strichliste2, i figures out what the problem was - something changed on travis side with cleanup.
